---
title: "St. Louis Lead Inequity"
author: "Alessandra Vidal Meza"
format: html
editor: visual
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
```

## First, let's load the data using the *here* function and clean the column names.

```{r}
stl_lead <- read.csv(here::here("data", 
                                "stl_blood_lead.csv"), 
                     sep = ";") %>% 
    clean_names() %>%
  mutate(pct_elevated = as.numeric(str_replace(pct_elevated,",",".")))
```

## Now, let's make a data frame and create a new variable.
```{r}
stl_lead_prop <- stl_lead %>% 
  mutate(prop_white = (white / total_pop) * 100)

stl_lead_prop$pct_elevated <- as.numeric(stl_lead_prop$pct_elevated)
# Same thing as
# stl_lead_prop$prop_white = stl_lead_prop$white / stl_lead_prop$total_pop * 100
```

## Next, let's make a scatterplot.
```{r fig.height=6, fig.width=5}
stl_lead_plot <- ggplot(data = stl_lead_prop,
                                 aes(x=prop_white,
                                     y=pct_elevated))+
  geom_point(alpha=0.5) +
  labs(x = "People in census tract identifying as white (%)",
       y= "Children in census tract with elevated blood lead  (%)",
       title = "Elevated blood lead versus white children in St. Louis")

stl_lead_plot

ggsave(plot=stl_lead_plot,
       here::here("figs",
                  "stl_lead_plot.png"),
       width=6,
       height=5,
       dpi=200)

```

We observe that census tracts with lower percentages of people identifiyng as white relate to census tracts with greater percentages of children with elevated blood lead levels.

## Now let's make a histogram. 
```{r fig.height=8, fig.width=6}
pctElevated_histo <- ggplot(data=stl_lead_prop, 
                            aes(x=pct_elevated)) +
  geom_histogram(color="#ED6A5E",
                     fill="#ED6A5E") +
  labs(title = "Children in census tract with elevated blood lead levels")

pctElevated_histo

ggsave(plot=pctElevated_histo,
       here::here("figs",
                  "pctElevated_histo.jpg"),
       width=8,
       height=6,
       dpi=200)
```

